name = "blog-charmanita-dev"
compatibility_date = "2026-05-29"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[vars]
BREVO_LIST_ID = "3"

[assets]
directory = ".svelte-kit/cloudflare"